# Generated by Django 4.0.2 on 2022-02-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='year_of_production',
            field=models.DateField(null=True),
        ),
    ]
