# Generated by Django 4.0.2 on 2022-02-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_cars_year_of_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='year_of_production',
            field=models.CharField(max_length=4),
        ),
    ]
