# Generated by Django 4.0.2 on 2022-02-21 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_manufacturer_alter_cars_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.manufacturer'),
        ),
    ]
